server:
  port: ${PORT:8080}

spring:
  application:
    name: flowforge-backend
  config:
    import: "optional:file:.env[.properties]"
  mongodb:
    database: flowforge

app:
  mongodb:
    uri-template: "mongodb+srv://{username}:{password}@flowforge-mongodb-clust.thmx8ml.mongodb.net/flowforge"
    encrypted-username: "X5CSqtoLJxJMZxIqCyXQ1bydvqxoFXWMFwKGEAVl0dbRJ2IVfSNcFgRunNDFbhiruA=="
    encrypted-password: "UHngArFexRnHrDqV/qiP1MxB9EvFkK6Qqldxvw8CQpRE/tZItFxWZESTYj0="
    encryption-key: ${MONGO_ENCRYPTION_KEY}

jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
    #port: 8000

logging:
  level:
    com.flowforge: DEBUG