server:
  port: 8080

spring:
  application:
    name: flowforge-backend
  mongodb:
    uri: mongodb+srv://06ritadhwaj29_db_user:FHl4HLkyWcHKo0GG@flowforge-mongodb-clust.thmx8ml.mongodb.net/flowforge
    database: flowforge

jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
    port: 8000

logging:
  level:
    com.flowforge: DEBUG